dev:
  wait: 15
  fast_pull_frequency: 0.1
  screen_size: "window-size=1920x1080"
  headless: '--headless'
  no_sandbox: '--no-sandbox'
  basic_auth: "the-internet.herokuapp.com/basic_auth"
  alert_basic: "https://the-internet.herokuapp.com/javascript_alerts"
  context_url: 'https://the-internet.herokuapp.com/context_menu'
  slider_url: 'https://the-internet.herokuapp.com/horizontal_slider'
  hovers_url: 'https://the-internet.herokuapp.com/hovers'
  handlers_url: 'https://the-internet.herokuapp.com/windows'
  iframe_url: https://demoqa.com/frames
  dynamic_url: https://the-internet.herokuapp.com/dynamic_content
  scroll_url: 'https://the-internet.herokuapp.com/infinite_scroll'
  upload_url: 'https://the-internet.herokuapp.com/upload'


